import type { QuestCategory } from '../database/models/quest.model';

export interface SeedQuestDefinition {
  code: string;
  emoji: string;
  name: string;
  description: string;
  category: QuestCategory;
  rule: string;
  target: number;
  params: Record<string, unknown>;
  duration_minutes: number;
  reward_cm: number;
  penalty_cm: number;
  cooldown_hours: number;
}

const HOUR = 60;
const DAY = 24 * HOUR;

/**
 * 32 стартові квести — джерело правди для database/seed.ts і для тесту
 * quest.rules.test.ts (кожне правило реєстру мусить обслуговувати хоча б
 * один квест звідси, і навпаки). Числа й тексти — з розділу «Стартовий набір
 * квестів» code-plans/PLAN-quests.md, не переописувати деінде.
 */
export const QUEST_SEED: SeedQuestDefinition[] = [
  // --- 🧘 Утримання (restraint) ---
  {
    code: 'vow_silence',
    emoji: '🧘',
    name: 'Обітниця тиші',
    description: '12 год без жодного виміру.',
    category: 'restraint',
    rule: 'no_measurement',
    target: 1,
    params: {},
    duration_minutes: 12 * HOUR,
    reward_cm: 6,
    penalty_cm: 5,
    cooldown_hours: 24,
  },
  {
    code: 'dry_law',
    emoji: '🌵',
    name: 'Сухий закон',
    description: '24 год без жодної дуелі.',
    category: 'restraint',
    rule: 'no_duel',
    target: 1,
    params: {},
    duration_minutes: 24 * HOUR,
    reward_cm: 7,
    penalty_cm: 6,
    cooldown_hours: 48,
  },
  {
    code: 'flawless',
    emoji: '🛡',
    name: 'Бездоганний',
    description: '48 год без програної дуелі (дуелі дозволені — не можна лише їх програвати).',
    category: 'restraint',
    rule: 'no_duel_loss',
    target: 1,
    params: {},
    duration_minutes: 48 * HOUR,
    reward_cm: 14,
    penalty_cm: 10,
    cooldown_hours: 72,
  },
  {
    code: 'daylight_only',
    emoji: '☀️',
    name: 'Тільки вдень',
    description: '72 год без нічних вимірів (00:00–04:59 за Києвом).',
    category: 'restraint',
    rule: 'no_night_measurement',
    target: 1,
    params: {},
    duration_minutes: 72 * HOUR,
    reward_cm: 12,
    penalty_cm: 8,
    cooldown_hours: 96,
  },
  {
    code: 'no_wobble',
    emoji: '🔒',
    name: 'Без хитань',
    description: '7 днів не міняти режим гри.',
    category: 'restraint',
    rule: 'no_mode_switch',
    target: 1,
    params: {},
    duration_minutes: 7 * DAY,
    reward_cm: 10,
    penalty_cm: 8,
    cooldown_hours: 168,
  },
  {
    code: 'keep_the_chain',
    emoji: '⛓',
    name: 'Не рви серію',
    description: '48 год без жодного запізнення.',
    category: 'restraint',
    rule: 'no_streak_break',
    target: 1,
    params: {},
    duration_minutes: 48 * HOUR,
    reward_cm: 13,
    penalty_cm: 10,
    cooldown_hours: 72,
  },
  {
    code: 'no_dips',
    emoji: '🩹',
    name: 'Без провалів',
    description: '24 год: жоден вимір не гірший за −4 см.',
    category: 'restraint',
    rule: 'no_bad_measurement',
    target: 1,
    params: { maxDip: 4 },
    duration_minutes: 24 * HOUR,
    reward_cm: 9,
    penalty_cm: 7,
    cooldown_hours: 24,
  },
  {
    code: 'penny_pincher',
    emoji: '🪙',
    name: 'Скупий',
    description: '48 год не приймати дуелей зі ставкою > 5 см.',
    category: 'restraint',
    rule: 'no_big_stake',
    target: 1,
    params: { maxStake: 5 },
    duration_minutes: 48 * HOUR,
    reward_cm: 8,
    penalty_cm: 6,
    cooldown_hours: 48,
  },

  // --- ⏱ Точність (precision) ---
  {
    code: 'clockwork_run',
    emoji: '🕰',
    name: 'Годинник',
    description: '4 виміри поспіль секунда-в-секунду, без жодного запізнення.',
    category: 'precision',
    rule: 'punctual_chain',
    target: 4,
    params: {},
    duration_minutes: 20 * HOUR,
    reward_cm: 12,
    penalty_cm: 9,
    cooldown_hours: 48,
  },
  {
    code: 'morning_shift',
    emoji: '🌅',
    name: 'Ранкова зміна',
    description: 'Вимір у вікні 06:00–09:00 у 3 різні дні.',
    category: 'precision',
    rule: 'hour_window_days',
    target: 3,
    params: { from: 6, to: 9 },
    duration_minutes: 72 * HOUR,
    reward_cm: 11,
    penalty_cm: 8,
    cooldown_hours: 96,
  },
  {
    code: 'midnight_run',
    emoji: '🌌',
    name: 'Опівнічний рейс',
    description: 'Вимір у вікні 00:00–01:00 у 2 різні доби.',
    category: 'precision',
    rule: 'hour_window_days',
    target: 2,
    params: { from: 0, to: 1 },
    duration_minutes: 48 * HOUR,
    reward_cm: 12,
    penalty_cm: 9,
    cooldown_hours: 72,
  },
  {
    code: 'no_gap_days',
    emoji: '🗓',
    name: 'Без пропусків',
    description: 'Хоча б один вимір у кожен із 3 календарних днів поспіль.',
    category: 'precision',
    rule: 'distinct_days',
    target: 3,
    params: {},
    duration_minutes: 72 * HOUR,
    reward_cm: 10,
    penalty_cm: 7,
    cooldown_hours: 96,
  },
  {
    code: 'exact_five',
    emoji: '⚖️',
    name: "Рівно п'ять",
    description: "Рівно 5 вимірів за добу — ні більше, ні менше.",
    category: 'precision',
    rule: 'exact_measurements',
    target: 5,
    params: {},
    duration_minutes: 24 * HOUR,
    reward_cm: 12,
    penalty_cm: 10,
    cooldown_hours: 48,
  },
  {
    code: 'lucky_streak',
    emoji: '🍀',
    name: 'Смуга удачі',
    description: '3 виміри поспіль у плюс (будь-який мінус обнуляє).',
    category: 'precision',
    rule: 'positive_chain',
    target: 3,
    params: {},
    duration_minutes: 24 * HOUR,
    reward_cm: 12,
    penalty_cm: 9,
    cooldown_hours: 48,
  },

  // --- 🏆 Позиція (position) ---
  {
    code: 'hold_throne',
    emoji: '👑',
    name: 'Утримай трон',
    description: 'На дедлайні бути №1 у рейтингу чату.',
    category: 'position',
    rule: 'rank_at_most',
    target: 1,
    params: { maxRank: 1 },
    duration_minutes: 24 * HOUR,
    reward_cm: 20,
    penalty_cm: 14,
    cooldown_hours: 72,
  },
  {
    code: 'stay_top3',
    emoji: '🏅',
    name: 'Тримайся трійки',
    description: 'На дедлайні бути в топ-3 чату.',
    category: 'position',
    rule: 'rank_at_most',
    target: 1,
    params: { maxRank: 3 },
    duration_minutes: 48 * HOUR,
    reward_cm: 14,
    penalty_cm: 10,
    cooldown_hours: 72,
  },
  {
    code: 'one_step_up',
    emoji: '🪜',
    name: 'На сходинку вище',
    description: 'На дедлайні бути вище в рейтингу, ніж на старті.',
    category: 'position',
    rule: 'rank_improved',
    target: 1,
    params: {},
    duration_minutes: 24 * HOUR,
    reward_cm: 11,
    penalty_cm: 8,
    cooldown_hours: 48,
  },
  {
    code: 'above_average',
    emoji: '📊',
    name: 'Вище середнього',
    description: 'Приріст за вікно ≥ середнього по активних гравцях чату.',
    category: 'position',
    rule: 'beat_chat_average',
    target: 1,
    params: {},
    duration_minutes: 24 * HOUR,
    reward_cm: 13,
    penalty_cm: 9,
    cooldown_hours: 48,
  },
  {
    code: 'precise_ten',
    emoji: '🎯',
    name: 'Точно десять',
    description: 'Чистий приріст за вікно = 10 см ± 1.5.',
    category: 'position',
    rule: 'growth_in_range',
    target: 10,
    params: { tolerance: 1.5 },
    duration_minutes: 24 * HOUR,
    reward_cm: 16,
    penalty_cm: 11,
    cooldown_hours: 48,
  },
  {
    code: 'precise_five',
    emoji: '🎯',
    name: "Точно п'ять",
    description: 'Чистий приріст за вікно = 5 см ± 1.',
    category: 'position',
    rule: 'growth_in_range',
    target: 5,
    params: { tolerance: 1 },
    duration_minutes: 12 * HOUR,
    reward_cm: 12,
    penalty_cm: 9,
    cooldown_hours: 24,
  },
  {
    code: 'climb_two',
    emoji: '🧗',
    name: 'Дві сходинки',
    description: 'На дедлайні бути щонайменше на 2 позиції вище, ніж на старті.',
    category: 'position',
    rule: 'rank_improved',
    target: 1,
    params: { minSteps: 2 },
    duration_minutes: 48 * HOUR,
    reward_cm: 15,
    penalty_cm: 11,
    cooldown_hours: 72,
  },
  {
    code: 'deep_dive',
    emoji: '🕳',
    name: 'Глибоке занурення',
    description: 'У режимі буріння поглибитись на 8 см ± 2 за добу.',
    category: 'position',
    rule: 'growth_in_range',
    target: 8,
    params: { tolerance: 2, requireMode: ['drill'] },
    duration_minutes: 24 * HOUR,
    reward_cm: 12,
    penalty_cm: 9,
    cooldown_hours: 48,
  },

  // --- 🎲 Удача (luck) ---
  {
    code: 'crit_before_dawn',
    emoji: '💥',
    name: 'Крит до світанку',
    description: 'Зловити критичну умову за 12 год.',
    category: 'luck',
    rule: 'condition_in_window',
    target: 1,
    params: { codes: ['critical'] },
    duration_minutes: 12 * HOUR,
    reward_cm: 18,
    penalty_cm: 12,
    cooldown_hours: 48,
  },
  {
    code: 'three_faces',
    emoji: '🎭',
    name: 'Три обличчя',
    description: '3 РІЗНІ спецумови за добу.',
    category: 'luck',
    rule: 'distinct_conditions',
    target: 3,
    params: {},
    duration_minutes: 24 * HOUR,
    reward_cm: 14,
    penalty_cm: 10,
    cooldown_hours: 48,
  },
  {
    code: 'weather_window',
    emoji: '🌦',
    name: 'Погодне вікно',
    description: '2 погодні умови за добу.',
    category: 'luck',
    rule: 'condition_in_window',
    target: 2,
    params: { codes: ['weather'] },
    duration_minutes: 24 * HOUR,
    reward_cm: 10,
    penalty_cm: 7,
    cooldown_hours: 48,
  },
  {
    code: 'market_session',
    emoji: '💹',
    name: 'Біржова сесія',
    description: 'Крипто- або валютна умова за 8 год.',
    category: 'luck',
    rule: 'condition_in_window',
    target: 1,
    params: { codes: ['crypto', 'currency'] },
    duration_minutes: 8 * HOUR,
    reward_cm: 11,
    penalty_cm: 8,
    cooldown_hours: 24,
  },
  {
    code: 'moon_window',
    emoji: '🌕',
    name: 'Місячне вікно',
    description: 'Умова фази місяця за 18 год.',
    category: 'luck',
    rule: 'condition_in_window',
    target: 1,
    params: { codes: ['moon_phase'] },
    duration_minutes: 18 * HOUR,
    reward_cm: 12,
    penalty_cm: 9,
    cooldown_hours: 48,
  },
  {
    code: 'one_big_hit',
    emoji: '🚀',
    name: 'Один великий',
    description: 'Вимір із приростом ≥ 8 см за 12 год.',
    category: 'luck',
    rule: 'big_hit',
    target: 1,
    params: { minDelta: 8 },
    duration_minutes: 12 * HOUR,
    reward_cm: 13,
    penalty_cm: 9,
    cooldown_hours: 24,
  },

  // --- ⚔️ Дуельні (duel) ---
  {
    code: 'strike_first',
    emoji: '🌃',
    name: 'Виклик до ночі',
    description: 'Виграти дуель, яку ти сам ініціював, за 6 год.',
    category: 'duel',
    rule: 'win_initiated',
    target: 1,
    params: {},
    duration_minutes: 6 * HOUR,
    reward_cm: 12,
    penalty_cm: 9,
    cooldown_hours: 24,
  },
  {
    code: 'revenge',
    emoji: '🔁',
    name: 'Реванш',
    description: 'Виграти в того, хто переміг тебе останнім.',
    category: 'duel',
    rule: 'win_revenge',
    target: 1,
    params: {},
    duration_minutes: 48 * HOUR,
    reward_cm: 16,
    penalty_cm: 12,
    cooldown_hours: 72,
  },
  {
    code: 'all_in',
    emoji: '🎰',
    name: 'Ва-банк',
    description: 'Виграти дуель зі ставкою ≥ 10 см.',
    category: 'duel',
    rule: 'win_high_stake',
    target: 1,
    params: { minStake: 10 },
    duration_minutes: 24 * HOUR,
    reward_cm: 15,
    penalty_cm: 11,
    cooldown_hours: 48,
  },
  {
    code: 'underdog',
    emoji: '🐕',
    name: 'Аутсайдер',
    description: 'Виграти в гравця, чий прогрес більший за твій.',
    category: 'duel',
    rule: 'win_underdog',
    target: 1,
    params: {},
    duration_minutes: 24 * HOUR,
    reward_cm: 14,
    penalty_cm: 10,
    cooldown_hours: 48,
  },
];
