import { nowUtc } from '../utils/date.util';
import { progress as playerProgress } from '../utils/mode.util';
import type { AchievementDefinition, AchievementMetricContext } from './achievement.types';

const counter = (key: string) => (ctx: AchievementMetricContext) => ctx.progress.counters?.get(key) ?? 0;
const hits = (...codes: string[]) => (ctx: AchievementMetricContext) =>
  codes.reduce((sum, code) => sum + (ctx.progress.condition_hits?.get(code) ?? 0), 0);

/** Скільки РІЗНИХ кодів умов хоч раз спрацювали цьому гравцю. */
function distinctConditionHits(ctx: AchievementMetricContext): number {
  const conditionHits = ctx.progress.condition_hits;
  if (!conditionHits) return 0;
  let count = 0;
  for (const value of conditionHits.values()) {
    if (value > 0) count += 1;
  }
  return count;
}

export const ACHIEVEMENTS: readonly AchievementDefinition[] = [
  // --- 📏 Виміри ---
  {
    code: 'meter',
    emoji: '📏',
    name: 'Метроман',
    hint: 'Роби виміри',
    category: 'measure',
    unit: 'count',
    thresholds: [50, 200, 600, 1500],
    rewards: [5, 10, 20, 50],
    value: counter('total_measurements'),
  },
  {
    code: 'clockwork',
    emoji: '⏰',
    name: 'Точний як годинник',
    hint: 'Тримай серію вчасних вимірів',
    category: 'measure',
    unit: 'count',
    thresholds: [10, 30, 75, 200],
    rewards: [5, 10, 20, 50],
    value: (ctx) => ctx.user.streak_best,
  },
  {
    code: 'nightshift',
    emoji: '🌙',
    name: 'Нічна зміна',
    hint: 'Вимірюй уночі (00:00–04:59 за Києвом)',
    category: 'measure',
    unit: 'count',
    thresholds: [5, 25, 75, 200],
    rewards: [4, 9, 17, 45],
    value: counter('night_measurements'),
  },
  {
    code: 'veteran',
    emoji: '🎖',
    name: 'Старожил',
    hint: 'Залишайся в грі',
    category: 'measure',
    unit: 'days',
    thresholds: [7, 30, 120, 365],
    rewards: [3, 8, 15, 40],
    value: (ctx) => Math.floor(nowUtc().diff(ctx.user.created_at, 'day', true)),
  },
  {
    code: 'punctual',
    emoji: '⚡',
    name: 'Секунда в секунду',
    hint: 'Вимірюй одразу після завершення кулдауну',
    category: 'measure',
    unit: 'count',
    thresholds: [5, 25, 75, 200],
    rewards: [4, 9, 17, 45],
    value: counter('punctual_measurements'),
  },

  // --- 📈 Прогрес ---
  {
    code: 'size',
    emoji: '🍆',
    name: 'Габарити',
    hint: 'Досягни піку прогресу',
    category: 'growth',
    unit: 'cm',
    thresholds: [30, 75, 150, 300],
    rewards: [5, 10, 20, 50],
    // max(), а не просто лічильник: власна нагорода досягнень (яка теж рухає
    // value через buildClampedValueUpdate) мусить одразу враховуватись у піку,
    // інакше каскад (Зафіксовані рішення, п.5) ніколи б не спрацював - лічильник
    // рухає лише реальний вимір, а не сам факт видачі см.
    value: (ctx) => Math.max(ctx.progress.counters?.get('peak_progress') ?? 0, playerProgress(ctx.user.value, ctx.user.mode)),
  },
  {
    code: 'jump',
    emoji: '🚀',
    name: 'Стрибок',
    hint: 'Злови найбільший приріст за один вимір',
    category: 'growth',
    unit: 'cm',
    thresholds: [8, 15, 30, 60],
    rewards: [4, 9, 18, 45],
    value: counter('best_progress_delta'),
  },
  {
    code: 'season_rush',
    emoji: '📈',
    name: 'Сезонний ривок',
    hint: 'Вирости за один сезон',
    category: 'growth',
    unit: 'cm',
    thresholds: [40, 100, 200, 400],
    rewards: [5, 10, 20, 50],
    value: counter('best_season_growth'),
  },
  {
    code: 'slump',
    emoji: '💀',
    name: 'Чорна смуга',
    hint: 'Переживи найгірший вимір',
    category: 'growth',
    unit: 'cm',
    thresholds: [8, 15, 30, 60],
    rewards: [3, 8, 15, 40],
    value: (ctx) => Math.abs(ctx.progress.counters?.get('worst_progress_delta') ?? 0),
  },
  {
    code: 'driller',
    emoji: '🕳',
    name: 'Буровик',
    hint: 'Вимірюй у режимі буріння',
    category: 'growth',
    unit: 'count',
    thresholds: [25, 100, 300, 800],
    rewards: [4, 9, 17, 45],
    value: counter('drill_measurements'),
  },

  // --- ⚔️ Дуелі ---
  {
    code: 'duelist',
    emoji: '⚔️',
    name: 'Дуелянт',
    hint: 'Бери участь у дуелях',
    category: 'duel',
    unit: 'count',
    thresholds: [5, 25, 75, 200],
    rewards: [4, 9, 17, 45],
    value: counter('duel_total'),
  },
  {
    code: 'winner',
    emoji: '🏆',
    name: 'Переможець',
    hint: 'Вигравай дуелі',
    category: 'duel',
    unit: 'count',
    thresholds: [3, 15, 45, 120],
    rewards: [5, 10, 20, 50],
    value: counter('duel_wins'),
  },
  {
    code: 'win_streak',
    emoji: '🔥',
    name: 'Серія перемог',
    hint: 'Вигравай дуелі поспіль',
    category: 'duel',
    unit: 'count',
    thresholds: [3, 5, 8, 12],
    rewards: [5, 10, 20, 50],
    value: counter('duel_win_streak_best'),
  },
  {
    code: 'highroller',
    emoji: '🎰',
    name: 'Хайроллер',
    hint: 'Вигравай дуелі на великі ставки',
    category: 'duel',
    unit: 'cm',
    thresholds: [15, 40, 90, 200],
    rewards: [4, 9, 18, 45],
    value: counter('max_stake_won'),
  },
  {
    code: 'bully',
    emoji: '🗡',
    name: 'Задирака',
    hint: 'Викликай гравців на дуель',
    category: 'duel',
    unit: 'count',
    thresholds: [5, 25, 60, 150],
    rewards: [3, 8, 15, 40],
    value: counter('duel_initiated_accepted'),
  },
  {
    code: 'defender',
    emoji: '🛡',
    name: 'Незламний',
    hint: 'Відбивай чужі виклики на дуель',
    category: 'duel',
    unit: 'count',
    thresholds: [3, 12, 35, 90],
    rewards: [4, 9, 17, 45],
    value: counter('duel_defended_wins'),
  },

  // --- 🎲 Умови ---
  {
    code: 'critical',
    emoji: '💥',
    name: 'Критичний',
    hint: 'Злови критичну умову виміру',
    category: 'condition',
    unit: 'count',
    thresholds: [1, 5, 20, 50],
    rewards: [5, 10, 20, 50],
    value: hits('critical'),
  },
  {
    code: 'meteo',
    emoji: '🌦',
    name: 'Метеозалежний',
    hint: 'Злови погодну умову',
    category: 'condition',
    unit: 'count',
    thresholds: [5, 25, 75, 200],
    rewards: [3, 8, 15, 40],
    value: hits('weather'),
  },
  {
    code: 'lunatic',
    emoji: '🌕',
    name: 'Лунатик',
    hint: 'Злови умову фази місяця',
    category: 'condition',
    unit: 'count',
    thresholds: [5, 25, 75, 200],
    rewards: [3, 8, 15, 40],
    value: hits('moon_phase'),
  },
  {
    code: 'trader',
    emoji: '💹',
    name: 'Трейдер',
    hint: 'Злови умову крипти чи валюти',
    category: 'condition',
    unit: 'count',
    thresholds: [5, 25, 75, 200],
    rewards: [3, 8, 15, 40],
    value: hits('crypto', 'currency'),
  },
  {
    code: 'collector',
    emoji: '🧾',
    name: 'Колекціонер умов',
    hint: 'Злови якомога більше різних умов',
    category: 'condition',
    unit: 'count',
    thresholds: [3, 5, 7, 8],
    rewards: [5, 10, 20, 50],
    value: distinctConditionHits,
  },

  // --- 🏅 Рейтинги ---
  {
    code: 'champion',
    emoji: '🥇',
    name: 'Чемпіон',
    hint: 'Здобувай титули за сезон',
    category: 'social',
    unit: 'count',
    thresholds: [1, 3, 6, 12],
    rewards: [5, 10, 20, 50],
    value: (ctx) => ctx.user.titles?.length ?? 0,
  },
  {
    code: 'crown',
    emoji: '👑',
    name: 'Корона',
    hint: 'Займай перше місце сезону',
    category: 'social',
    unit: 'count',
    thresholds: [1, 2, 4, 8],
    rewards: [5, 10, 20, 50],
    value: (ctx) => ctx.user.titles?.filter((t) => t.rank === 1).length ?? 0,
  },
  {
    code: 'holder',
    emoji: '🎯',
    name: 'Тримає топ',
    hint: 'Фінішуй раунд у топ-3 чату',
    category: 'social',
    unit: 'count',
    thresholds: [1, 5, 15, 40],
    rewards: [4, 9, 17, 45],
    value: counter('top3_round_finishes'),
  },
  {
    code: 'climber',
    emoji: '🧗',
    name: 'Альпініст',
    hint: 'Увірвись у топ-3, якого не було на старті раунду',
    category: 'social',
    unit: 'count',
    thresholds: [1, 3, 8, 20],
    rewards: [4, 9, 17, 45],
    value: counter('climber_entries'),
  },
  {
    code: 'traveler',
    emoji: '🌍',
    name: 'Мандрівник',
    hint: 'Будь активним у кількох чатах',
    category: 'social',
    unit: 'count',
    thresholds: [1, 2, 4, 7],
    rewards: [3, 8, 15, 40],
    value: (ctx) => ctx.user.chats?.length ?? 0,
  },
  {
    code: 'exp',
    emoji: '🧠',
    name: 'Досвід',
    hint: 'Накопичуй ранговий досвід',
    category: 'social',
    unit: 'count',
    thresholds: [20, 50, 100, 200],
    rewards: [3, 8, 15, 40],
    value: (ctx) => ctx.user.experience ?? 0,
  },

  // --- 🎭 Різне ---
  {
    code: 'twoface',
    emoji: '🔄',
    name: 'Дволикий',
    hint: 'Змінюй режим гри',
    category: 'meta',
    unit: 'count',
    thresholds: [1, 3, 10, 25],
    rewards: [3, 8, 15, 40],
    value: counter('mode_switches'),
  },
  {
    code: 'marathon',
    emoji: '🏃',
    name: 'Марафонець раунду',
    hint: 'Вимірюй якомога частіше в межах одного раунду',
    category: 'meta',
    unit: 'count',
    thresholds: [12, 24, 36, 42],
    rewards: [5, 10, 20, 50],
    value: counter('best_round_measurement_count'),
  },
  {
    code: 'themed',
    emoji: '🎭',
    name: 'Тематичний',
    hint: 'Вимірюй під час тематичних подій',
    category: 'meta',
    unit: 'count',
    thresholds: [10, 40, 100, 250],
    rewards: [3, 8, 15, 40],
    value: counter('theme_measurements'),
  },
];

export const ACHIEVEMENTS_BY_CODE = new Map(ACHIEVEMENTS.map((a) => [a.code, a]));
export const ACHIEVEMENT_LEVELS = 4;
export const TOTAL_ACHIEVEMENT_LEVELS = ACHIEVEMENTS.length * ACHIEVEMENT_LEVELS; // 120
